services:
  nginx:
    image: nginx:alpine
    depends_on:
      - frontend
      - backend
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    expose:
      - "80"

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://root:password@mongodb:27017/todolist?authSource=admin
    expose:
      - "3000"

  mongodb:
    image: mongo:8.2
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
