services:
  nginx:
    image: nginx:alpine
    depends_on:
      - frontend
      - backend
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    expose:
      - "80"

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    depends_on:
      - dbms
    environment:
      PORT: 3000
      DB_HOST: dbms
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: postgres
    expose:
      - "3000"

  dbms:
    image: postgres:18.3-alpine3.23
    container_name: dbms
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
    volumes:
      - pgdata:/var/lib/postgresql/18/docker
      - ../backend/0_db.sql:/docker-entrypoint-initdb.d/0_db.sql
      - ../backend/1_dati.sql:/docker-entrypoint-initdb.d/1_dati.sql
    ports:
      - 5432:5432
    restart: unless-stopped

volumes:
  pgdata:
