-- Database Schema per Compagnia Aerea "FlyPlus"
-- Correzioni apportate:
-- 1. Uniformata la naming convention in lowercase per tabelle e colonne.
-- 2. Corretti i tipi di dato per i voli (TIMESTAMP invece di DECIMAL).
-- 3. Invertite le relazioni errate (es. prenotazioni -> utenti, non viceversa).
-- 4. Risolte le dipendenze circolari tra aeroporti e gate rendendo opzionali i vincoli ridondanti.
-- 5. Aggiunti indici per ottimizzare le performance delle query comuni.
-- 6. Organizzato l'ordine delle tabelle secondo le dipendenze logiche.
-- 7. Uniformata la naming convention delle colonne (nomi al singolare per le FK).

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

BEGIN;

-- --- PULIZIA SCHEMA (Opzionale, utile per sviluppo) ---
DROP TABLE IF EXISTS biglietti CASCADE;
DROP TABLE IF EXISTS prenotazioni CASCADE;
DROP TABLE IF EXISTS utenti CASCADE;
DROP TABLE IF EXISTS documenti CASCADE;
DROP TABLE IF EXISTS gate CASCADE;
DROP TABLE IF EXISTS voli CASCADE;
DROP TABLE IF EXISTS aeroporti CASCADE;
DROP TABLE IF EXISTS tratte CASCADE;
DROP TABLE IF EXISTS aerei CASCADE;

-- --- TABELLE ---

-- Tabella Aerei
CREATE TABLE IF NOT EXISTS aerei (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    capienza INTEGER NOT NULL,
    stato BOOLEAN NOT NULL DEFAULT TRUE, -- TRUE = operativo, FALSE = manutenzione
    modello VARCHAR(255) NOT NULL,
    CONSTRAINT pk_aerei PRIMARY KEY (id) 
);

-- Tabella Tratte
CREATE TABLE IF NOT EXISTS tratte (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(255) NOT NULL,
    CONSTRAINT pk_tratte PRIMARY KEY (id)
);

-- Tabella Aeroporti
CREATE TABLE IF NOT EXISTS aeroporti (
    nome VARCHAR(255) NOT NULL,
    aereo_id INTEGER, -- Riferimento all'aereo stazionato
    gate_id INTEGER,  -- Riferimento al gate principale
    citta VARCHAR(255) NOT NULL,
    CONSTRAINT pk_aeroporti PRIMARY KEY (nome)
);

-- Tabella Voli
CREATE TABLE IF NOT EXISTS voli (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    tratta_id INTEGER NOT NULL,
    aereo_id INTEGER NOT NULL,
    partenza TIMESTAMP NOT NULL,
    arrivo TIMESTAMP NOT NULL,
    CONSTRAINT pk_voli PRIMARY KEY (id)
);

-- Tabella Gate
CREATE TABLE IF NOT EXISTS gate (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    aeroporto_nome VARCHAR(255) NOT NULL,
    volo_id INTEGER, -- Volo attualmente assegnato al gate
    CONSTRAINT pk_gate PRIMARY KEY (id)
);

-- Tabella Documenti
CREATE TABLE IF NOT EXISTS documenti (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    utente_id INTEGER NOT NULL,
    documento BYTEA NOT NULL,
    CONSTRAINT pk_documenti PRIMARY KEY (id)
);

-- Tabella Utenti
CREATE TABLE IF NOT EXISTS utenti (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(255) NOT NULL,
    cognome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    documento_id INTEGER, -- Collegamento al documento d'identità
    CONSTRAINT pk_utenti PRIMARY KEY (id)
);

-- Tabella Prenotazioni
CREATE TABLE IF NOT EXISTS prenotazioni (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    utente_id INTEGER NOT NULL,
    passeggeri INTEGER NOT NULL DEFAULT 1,
    tratta_id INTEGER NOT NULL,
    CONSTRAINT pk_prenotazioni PRIMARY KEY (id)
);

-- Tabella Biglietti
CREATE TABLE IF NOT EXISTS biglietti (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    utente_id INTEGER NOT NULL,
    gate_id INTEGER NOT NULL,
    CONSTRAINT pk_biglietti PRIMARY KEY (id)
);

-- --- VINCOLI DI CHIAVE ESTERNA (FOREIGN KEYS) ---

-- Relazioni Aeroporti
ALTER TABLE aeroporti
    ADD CONSTRAINT fk_aeroporti_aerei FOREIGN KEY (aereo_id) REFERENCES aerei (id) ON DELETE SET NULL,
    ADD CONSTRAINT fk_aeroporti_gate FOREIGN KEY (gate_id) REFERENCES gate (id) ON DELETE SET NULL;

-- Relazioni Voli
ALTER TABLE voli
    ADD CONSTRAINT fk_voli_tratte FOREIGN KEY (tratta_id) REFERENCES tratte (id) ON DELETE CASCADE,
    ADD CONSTRAINT fk_voli_aerei FOREIGN KEY (aereo_id) REFERENCES aerei (id) ON DELETE CASCADE;

-- Relazioni Gate
ALTER TABLE gate
    ADD CONSTRAINT fk_gate_aeroporti FOREIGN KEY (aeroporto_nome) REFERENCES aeroporti (nome) ON DELETE CASCADE,
    ADD CONSTRAINT fk_gate_voli FOREIGN KEY (volo_id) REFERENCES voli (id) ON DELETE SET NULL;

-- Relazioni Documenti
ALTER TABLE documenti
    ADD CONSTRAINT fk_documenti_utenti FOREIGN KEY (utente_id) REFERENCES utenti (id) ON DELETE CASCADE;

-- Relazioni Utenti
ALTER TABLE utenti
    ADD CONSTRAINT fk_utenti_documenti FOREIGN KEY (documento_id) REFERENCES documenti (id) ON DELETE SET NULL;

-- Relazioni Prenotazioni
ALTER TABLE prenotazioni
    ADD CONSTRAINT fk_prenotazioni_utenti FOREIGN KEY (utente_id) REFERENCES utenti (id) ON DELETE CASCADE,
    ADD CONSTRAINT fk_prenotazioni_tratte FOREIGN KEY (tratta_id) REFERENCES tratte (id) ON DELETE CASCADE;

-- Relazioni Biglietti
ALTER TABLE biglietti
    ADD CONSTRAINT fk_biglietti_utenti FOREIGN KEY (utente_id) REFERENCES utenti (id) ON DELETE CASCADE,
    ADD CONSTRAINT fk_biglietti_gate FOREIGN KEY (gate_id) REFERENCES gate (id) ON DELETE RESTRICT;

-- --- INDICI PER OTTIMIZZAZIONE ---

CREATE INDEX idx_aeroporti_aereo ON aeroporti(aereo_id);
CREATE INDEX idx_aeroporti_gate ON aeroporti(gate_id);
CREATE INDEX idx_voli_tratta ON voli(tratta_id);
CREATE INDEX idx_voli_aereo ON voli(aereo_id);
CREATE INDEX idx_voli_partenza ON voli(partenza);
CREATE INDEX idx_gate_aeroporto ON gate(aeroporto_nome);
CREATE INDEX idx_gate_volo ON gate(volo_id);
CREATE INDEX idx_documenti_utente ON documenti(utente_id);
CREATE INDEX idx_utenti_email ON utenti(email);
CREATE INDEX idx_utenti_documento ON utenti(documento_id);
CREATE INDEX idx_prenotazioni_utente ON prenotazioni(utente_id);
CREATE INDEX idx_prenotazioni_tratta ON prenotazioni(tratta_id);
CREATE INDEX idx_biglietti_utente ON biglietti(utente_id);
CREATE INDEX idx_biglietti_gate ON biglietti(gate_id);

COMMIT;
